___

<a href='https://mainacademy.ua/'> <img src='https://mainacademy.ua/wp-content/uploads/2019/03/logo-main.png' alt = 'Хмм, щось з інтернетом'/></a>
___

# Module 5: Data analysis with NumPy and Pandas

## Lab work 5.1



#### Мета: 

* навчитися працювати із бібліотекою NumPy в Python

### Завдання:

In [1]:
import numpy as np

Вивести версію та конфігурацію бібліотеки:

In [2]:
print(np.__version__)


1.19.2


Створити вектор з 10 елементів, заповнений одиницями:

In [3]:
print(np.ones((10)))

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


Створити вектор із значеннями від 0 до 10:

In [4]:
print(np.arange(0,11))

[ 0  1  2  3  4  5  6  7  8  9 10]


Створити матрицю 5 на 5, заповнену нулями:

In [5]:
print(np.zeros((5,5)))

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


Заповнити вектор з 20 елементів випадковими цілими числами. Знайти індекси ненульових елементів:

In [6]:
s = np.random.random(20)
print(s)
i = np.nonzero(s)
print(i)

[0.44666984 0.3690591  0.35592796 0.35587505 0.14136533 0.46261987
 0.37568962 0.93462093 0.10981163 0.33580458 0.17181075 0.58337715
 0.61508937 0.5909615  0.74530573 0.4752865  0.99111649 0.78112935
 0.79297595 0.83658233]
(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19], dtype=int64),)


Для вектора із попередньої задачі знайти середнє значення, медіану, стандартне відхилення:

In [7]:
print(f'Середнє значення вектора s ==> {np.mean(s)}')
print(f'Медіана вектора s ==> {np.median(s)}')
print(f'Стандартне відхилення вектора s ==> {np.std(s)} \n')
print(f'Середнє значення вектора i ==> {np.mean(i)}')
print(f'Медіана вектора i ==> {np.median(i)}')
print(f'Стандартне відхилення вектора i ==> {np.std(i)} \n')

Середнє значення вектора s ==> 0.523553952284818
Медіана вектора s ==> 0.46895318664655433
Стандартне відхилення вектора s ==> 0.25301295098496 

Середнє значення вектора i ==> 9.5
Медіана вектора i ==> 9.5
Стандартне відхилення вектора i ==> 5.766281297335398 



Створити дві матриці випадкових чисел розміром 4х2 та 2х2. Перемножити їх:

In [8]:
z = np.random.random((4,2))
print(z)
x = np.random.random((2,2))
print(x)
q = z @ x
print(q)

[[0.70596219 0.91187796]
 [0.99778831 0.16953597]
 [0.33139851 0.1304089 ]
 [0.03427063 0.29927112]]
[[0.11989669 0.79489265]
 [0.70079465 0.75596886]]
[[0.72368173 1.2505155 ]
 [0.23844142 0.92129851]
 [0.13112344 0.36201131]
 [0.21383654 0.25348112]]


Результуючу матрицю із попередньої задачі перетворити у вектор. Знайти мінімальне та максимальне значення. 

Максимальне значення замінити на 0:

In [9]:
m = q.reshape((1,q.size)).copy()
print(f'вектор ==> {m}')
print(f'Мінімальне значення ==> {np.min(m)}')
print(f'Максимальне значення ==> {np.max(m)}')
m[m == np.max(m)] = 0
print(f'змінений вектор ==> {m}')

вектор ==> [[0.72368173 1.2505155  0.23844142 0.92129851 0.13112344 0.36201131
  0.21383654 0.25348112]]
Мінімальне значення ==> 0.1311234444578438
Максимальне значення ==> 1.2505154967188887
змінений вектор ==> [[0.72368173 0.         0.23844142 0.92129851 0.13112344 0.36201131
  0.21383654 0.25348112]]


Знайдіть кореляцію першого рядка матриці із попереднього завдання із іншими рядками:

In [10]:

arry = np.array([[0.77395605, 0.43887844, 0.85859792],
       [0.69736803, 0.09417735, 0.97562235],
       [0.7611397 , 0.78606431, 0.12811363]])
print(q) # це масив з попереднього завдання 
kx = np.corrcoef(q) # розрахунок кореляції для масиву q
print(kx) 
# мене здивувала матриця коефіцієнтів кореляції для масиву q. Для перевірки я взяв масив із документації
print(arry) 
ky = np.corrcoef(arry)
print(ky)

[[0.72368173 1.2505155 ]
 [0.23844142 0.92129851]
 [0.13112344 0.36201131]
 [0.21383654 0.25348112]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[0.77395605 0.43887844 0.85859792]
 [0.69736803 0.09417735 0.97562235]
 [0.7611397  0.78606431 0.12811363]]
[[ 1.          0.99256089 -0.68080987]
 [ 0.99256089  1.         -0.76492173]
 [-0.68080987 -0.76492173  1.        ]]


Дано матрицю. Знайти ранг матриці:

In [11]:
a = np.array([[ 1,  4, 5],
              [7, 3, 2],
              [9, 16, 1]])
print(np.linalg.matrix_rank(a))

3


Знайти визначник матриці:

In [12]:
np.linalg.det(a)

440.0000000000002

Знайти власні значення та власні вектори матриці: 

In [13]:
np.linalg.eig(a)

(array([14.13520334+0.j        , -4.56760167+3.20389947j,
        -4.56760167-3.20389947j]),
 array([[ 0.43131913+0.j        , -0.31386258-0.47450898j,
         -0.31386258+0.47450898j],
        [ 0.41502436+0.j        , -0.07049527+0.4090732j ,
         -0.07049527-0.4090732j ],
        [ 0.8010734 +0.j        ,  0.7099444 +0.j        ,
          0.7099444 -0.j        ]]))

Знайдіть число, що найчастіше зустрічається в масиві:

In [14]:
a = np.random.randint(0,10,50)

b = np.unique(a, return_counts=True)

print(f' Число {b[0][-1]} зустрічається у масиві найчастіше, а саме {b[1][-1]} разів')



 Число 9 зустрічається у масиві найчастіше, а саме 2 разів


Виведіть лише парні числа, що діляться на 5:

In [15]:
a = np.random.randint(0,10,50)
print(a)
b = a[(a%2 == 0) & (a%5 == 0)]
print(b)

[3 3 9 9 4 5 2 2 4 1 4 8 9 6 8 0 4 4 6 6 0 3 8 8 3 7 7 6 0 3 8 6 8 3 0 8 1
 1 9 2 7 1 4 8 6 3 3 7 3 4]
[0 0 0 0]


Розв'яжіть систему рівнянь:
$$2x + 5y = 1 $$

$$x - 10y = 3  $$
   

In [16]:
a = [[2, 5],
     [1, -10]]
b = [1,3]
x = np.linalg.solve(a, b)
print(x)

[ 1.  -0.2]
